Drug:
  Max_Nodes: 290

Protein:
    Max_Length: 1200
    After_CNN_Length: 1185

MBCA:
    Hidden_Size: 128
    Num_Heads: 8
    Attn_Dropout_Rate: 0.3

Global:
  Batch_Size: 32
  Max_Epoch: 100
  LR: 5e-5
  Seed: 42
